[tool.poetry]
name = "sinus-mat"
version = "0.1.0"
description = ""
authors = ["Pavel Hulevich"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
